### PR TITLE
Minor Bug fixes

### PR DESCRIPTION
**Pull request by Xoke**
1. Fixed cases of variables / commands
2. Fixed unlikely bug that if you ran it just before midnight, it would create a folder for one day, then try to save into the next day
3. Added checks for modules (if you run on a regular server it errors)
4. Corrected an Echo to have it echo one line out, not several
5. Tidied up the header comment a little

### CODE REVIEW

**Comment by 7MinSec** [comment]
Ok it says "This branch has conflicts that must be resolved" so I'll have to dive into that a bit.  I'm not understanding what exactly is a conflict besides that you're proposing changes.  As soon as I figure that out I'll accept 'em!

**Comment by Xoke** [comment]
If you made any changes, as I changed almost every line (case changes, 
anyway) it is probably confused.

------ Original Message ------

**Review by 7MinSec — APPROVED** [review]

**Comment by 7MinSec** [comment]
Huh...I'm still confused.  Will look at this later.  Looking at "resolve conflicts" it gives me these big chunks it marks as ">>>>>master" that I guess I'm supposed to delete to comment out, but if I do it doesn't appear I'll land at a correct version with all your changes.  Wonder if I should just copy/paste version from yours.

**Comment by 7MinSec** [comment]
Uhh....I *think* I did this right.  @Xoke ?

**Pull request closed without merging**
