### PR TITLE
Set-AdmPwdComputerSelfPermission is -identity, not -orgunit

### PR DESCRIPTION
**Pull request by Xoke**
there is no orgunit option, it is identity

### CODE REVIEW

**Comment by 7MinSec** [comment]
Thanks sir.  I did a refresh of the LAPS doc that I'll publish soon.  And then...I have no idea what that will do to your request, but lets revisit when that update is done and we'll go from there!

**Comment by 7MinSec** [comment]
Crap.  I think I updated BPATTY before incorporating your change a long time ago.  And I got more changes coming to this file with the next rev of BPATTY.  Then I'll revisit this request.

**Comment by 7MinSec** [comment]
Hey @Xoke Now that I've updated the .md on my side how can I gracefully resolve this?

**Comment by Xoke** [comment]
I'll close the pull request for you :)

**Comment by 7MinSec** [comment]
Sorry, I probably wasn't clear.  In the background I was making a zillion changes to the LAPS doc, then I committed those changes, and THEN I came back and looked at pull requests.  So essentially I think you might need to resubmit your pull changes against the current version of the doc?

**Comment by 7MinSec** [comment]
I'll close again as maybe it's best for you to make a new pull request.

**Pull request closed without merging**
